### ISSUE TITLE
Problem with fresh install

### ISSUE THREAD

**Issue by Roguyt** [dphuang2/PoGoBag#13]
Just install a fresh PogoBag with ngrok but i get this error when i try to render a player 

![screenshot from 2016-08-08 22-54-03](https://cloud.githubusercontent.com/assets/8149856/17495862/0cebc15e-5dbb-11e6-978a-2ef0be52774f.png)
Debian 8.0
On A VPS

**Comment by dphuang2** [comment]
#3
