### ISSUE TITLE
Problem when using proxy pass with nginx

### ISSUE THREAD

**Issue by Roguyt** [dphuang2/PoGoBag#18]
When i setup a proxy pass to access to PoGoBag, in the logs, the server return that he can't verify the CSRF token, do you have any idea from what is it ?
![capturerails](https://cloud.githubusercontent.com/assets/8149856/17512441/1b14eb94-5e28-11e6-89cc-6737a8f4407e.PNG)

**Comment by Roguyt** [comment]
Ok you just need to add those line to your nginx config, just like when you create a proxy for a nodejs app 
`        proxy_set_header   X-Real-IP $remote_addr;

        proxy_set_header X-Forwarded-For $remote_addr;

        proxy_set_header   Host      $http_host;
`

**Comment by Zerotask** [comment]
My sites-enabled/default looks like

` location /bag/ {
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_set_header   Host      $http_host;
                proxy_pass http://127.0.0.1:3000/;
         }

but it isn't working`

**Comment by Gordin** [comment]
This fixed the CSRF problem for me:  https://github.com/plataformatec/devise/pull/4033/files (Editing the controller file to 'protect_from_forgery prepend: true')

**Comment by Roguyt** [comment]
Here the block for the nginx config 

    location / {
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header   Host      $http_host;
        proxy_pass         http://127.0.0.1:3000/;
        proxy_connect_timeout       300;
        proxy_send_timeout          300;
        proxy_read_timeout          300;
        send_timeout                300;
    }

**Comment by Zerotask** [comment]
Thank Roguyt for your help. Unfortunately it doesn't work.

When I open domain.com/bag it refers to my logged in account: domain.com/accountname and all I see is a 404. What can it be?

**Comment by Roguyt** [comment]
Yeah i notice that too, you need to use youdomain.com instead of yourdomain.com/bag, because the link are hard coded. Maybe use a sub domain.
