### ISSUE TITLE
Discord server, and PR

### ISSUE THREAD

**Issue by goncalofalcao** [dphuang2/PoGoBag#19]
Would like to know if you have a discord server or slack for devs? And will you be accepting Pull Requests? Ruby developer here and i already made some (rough) changes on my local server. We could talk about it and maybe share the workload if you want.

**Comment by matenia** [comment]
:+1: on discord/slack

looks like prs are accepted (submitted 2 small fixes earlier and cleaning up some major refactor + improvements tomorrow)

**Comment by dphuang2** [comment]
Good idea, I will open one up right away.
