### ISSUE TITLE
[Feature Request] Show movesets

### ISSUE THREAD

**Issue by Zerotask** [dphuang2/PoGoBag#23]
It would be nice if you could see the attacks of each Pokemon.

**Comment by bugavka** [comment]
and Pokemon`s type

**Comment by haitianboy420** [comment]
agreeed

**Comment by pandacubed** [comment]
That would be awesome.
Oh, and their weaknesses.

The indivdual pokemon's stats could be with a pop up window or hover... though, I don't believe that hover-over is mobile friendly, so if all this goes over to the website version, pop ups are probably best since those work for sure on mobile.
