### ISSUE TITLE
problem during bundle install (Mac OSX)

### ISSUE THREAD

**Issue by ermwhyami** [dphuang2/PoGoBag#4]
Hi, I got the following error messages when I tried to install PoGoBag:-

> An error occurred while installing pg (0.18.4), and Bundler cannot continue.
> Make sure that `gem install pg -v '0.18.4'` succeeds before bundling.
> Jeffersons-iMac:PoGoBag jeffersontan$ gem install pg -v '0.18.4'
> Building native extensions.  This could take a while...
> ERROR:  Error installing pg:
> 	ERROR: Failed to build gem native extension.
> 
>     current directory: /Users/mainuser/.rvm/gems/ruby-2.3.0/gems/pg-0.18.4/ext
> /Users/mainuser/.rvm/rubies/ruby-2.3.0/bin/ruby -r ./siteconf20160808-42976-qmk2pu.rb extconf.rb
> checking for pg_config... no
> No pg_config... trying anyway. If building fails, please try again with
>  --with-pg-config=/path/to/pg_config
> checking for libpq-fe.h... no
> Can't find the 'libpq-fe.h header
> *** extconf.rb failed ***
> Could not create Makefile due to some reason, probably lack of necessary
> libraries and/or headers.  Check the mkmf.log file for more details.  You may
> need configuration options.

The mkmf.log file is as follows:-

> 
> find_executable: checking for pg_config... -------------------- no
> 
> --------------------
> 
> find_header: checking for libpq-fe.h... -------------------- no
> 
> "gcc -o conftest -I/Users/mainuser/.rvm/rubies/ruby-2.3.0/include/ruby-2.3.0/x86_64-darwin15 -I/Users/mainuser/.rvm/rubies/ruby-2.3.0/include/ruby-2.3.0/ruby/backward -I/Users/mainuser/.rvm/rubies/ruby-2.3.0/include/ruby-2.3.0 -I.  -I/usr/local/opt/libyaml/include -I/usr/local/opt/readline/include -I/usr/local/opt/libksba/include -I/usr/local/opt/openssl/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wshorten-64-to-32 -Wimplicit-function-declaration -Wdivision-by-zero -Wdeprecated-declarations -Wextra-tokens  -fno-common -pipe conftest.c  -L. -L/Users/mainuser/.rvm/rubies/ruby-2.3.0/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib     -lruby.2.3.0  -lpthread -ldl -lobjc "
> checked program was:
> /* begin */
> 1: #include "ruby.h"
> 2: 
> 3: int main(int argc, char **argv)
> 4: {
> 5:   return 0;
> 6: }
> /* end */
> 
> "gcc -E -I/Users/mainuser/.rvm/rubies/ruby-2.3.0/include/ruby-2.3.0/x86_64-darwin15 -I/Users/mainuser/.rvm/rubies/ruby-2.3.0/include/ruby-2.3.0/ruby/backward -I/Users/mainuser/.rvm/rubies/ruby-2.3.0/include/ruby-2.3.0 -I.  -I/usr/local/opt/libyaml/include -I/usr/local/opt/readline/include -I/usr/local/opt/libksba/include -I/usr/local/opt/openssl/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wshorten-64-to-32 -Wimplicit-function-declaration -Wdivision-by-zero -Wdeprecated-declarations -Wextra-tokens  -fno-common -pipe  conftest.c -o conftest.i"
> conftest.c:3:10: fatal error: 'libpq-fe.h' file not found
> #include <libpq-fe.h>
>          ^
> 1 error generated.
> checked program was:
> /* begin */
> 1: #include "ruby.h"
> 2: 
> 3: #include <libpq-fe.h>
> /* end */
> 
> --------------------

I'm using:-

> OS X El Capitan v 10.11.6
> ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
> Rails 5.0.0

Let me know if you need any more information

**Comment by JacobBum** [comment]
I'm getting this same problem

**Comment by lazloth** [comment]
try **xcode-select --install** at terminal

**Comment by ermwhyami** [comment]
Hi, thanks! I managed to install the gem file. However, I got the following error message after I tried to log in

> Sprockets::Rails::Helper::AssetNotPrecompiled in Users#show
> Showing /Users/mainuser/PoGoBag/app/views/pokemons/_pokemon.html.erb where line #18 raised:
> 
> Asset was not declared to be precompiled in production.
> Add `Rails.application.config.assets.precompile += %w( pokemon.css )` to `config/initializers/assets.rb` and restart your server
> Extracted source (around line #9):
> 7
> 8
> 9
> 10
> 11
>               
>     pokemon_hash = JSON.parse(file)
>     number = format("%03d", number)
>     image_tag("pokemon/"+/[0-9]{3}.{10}.png/.match(Dir["app/assets/images/pokemon/#{number}*"][0]).to_s) 
>   end
> end
> 
> Trace of template inclusion: app/views/users/show.html.erb
> 
> Rails.root: /Users/mainuser/PoGoBag
> 
> Application Trace | Framework Trace | Full Trace
> app/helpers/users_helper.rb:9:in `pokemon_image'
> app/views/pokemons/_pokemon.html.erb:18:in `_app_views_pokemons__pokemon_html_erb___1120750823044816035_70268489727080'
> app/views/users/show.html.erb:8:in `block in _app_views_users_show_html_erb___4289635446926380378_70268497925200'
> app/views/users/show.html.erb:5:in `_app_views_users_show_html_erb___4289635446926380378_70268497925200'

> 
> Request
> 
> Parameters:
> 
> {"id"=>"mytrainerid"}
> Toggle session dump
> _csrf_token: "UUL9qgPrlIt1xmvvQkdYzb7rEgTJGISgCHMhyDiIAf8="
> pogo_alias: "mytrainerid"
> session_id: "ad2e18e2db2931ded0efb47c53f75364"
> Toggle env dump
> GATEWAY_INTERFACE: "CGI/1.2"
> HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
> HTTP_ACCEPT_ENCODING: "gzip, deflate, sdch"
> HTTP_ACCEPT_LANGUAGE: "en-US,en;q=0.8"
> HTTP_CACHE_CONTROL: "max-age=0"
> HTTP_VERSION: "HTTP/1.1"
> ORIGINAL_SCRIPT_NAME: ""
> REMOTE_ADDR: "::1"
> SERVER_NAME: "localhost"
> SERVER_PROTOCOL: "HTTP/1.1"
> Response
> 
> Headers:
> 
> None

**Comment by lazloth** [comment]
Edit the file as per `Add **Rails.application.config.assets.precompile += %w( pokemon.css )** to **config/initializers/assets.r**b and restart your server` and you should be good to go

**Comment by lazloth** [comment]
Edit the file as per `Add Rails.application.config.assets.precompile += %w( pokemon.css ) to config/initializers/assets.r and restart your server` and you should be good to go

**Comment by ermwhyami** [comment]
Thanks it works now!
