### ISSUE TITLE
[Feature Request] provide configuration to allow non-localhost connections 

### ISSUE THREAD

**Issue by pyr0ball** [dphuang2/PoGoBag#42]
I want to be able to connect to the server from other local computers and/or via port forwarding. Setting bind tcp in puma config did not seem to work. Any way to build a configuration option to bind to a system's ip?

**Comment by Chris221** [comment]
rails s -b 0.0.0.0 -p 6000
-b binds an IP
-p binds a Port

**Comment by pyr0ball** [comment]
Fantastic! Can we add this to the Readme?

**Comment by dphuang2** [comment]
ngrok is a super great alternative to port-forwarding. I wrote instructions in the README already.

**Comment by pyr0ball** [comment]
Ngrok is not a great option for people like me who are network admins, especially if the solution is an easy argument to pass along with the terminal command
