### ISSUE TITLE
Problem bundel (Mac OS x)

### ISSUE THREAD

**Issue by RubenHiem** [dphuang2/PoGoBag#5]
Hi all,

I get the following error:

An error occurred while installing pg (0.18.4), and Bundler cannot continue.
Make sure that `gem install pg -v '0.18.4'` succeeds before bundling.

And if I do: gem install pg -v '0.18.4', I get the follow error:

uilding native extensions.  This could take a while...
ERROR:  Error installing pg:
	ERROR: Failed to build gem native extension.

    current directory: /Users/ss/.rvm/gems/ruby-2.3.0/gems/pg-0.18.4/ext
/Users/ss/.rvm/rubies/ruby-2.3.0/bin/ruby -r ./siteconf20160808-61172-1gqloum.rb extconf.rb
checking for pg_config... no
No pg_config... trying anyway. If building fails, please try again with
 --with-pg-config=/path/to/pg_config
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/ss/.rvm/rubies/ruby-2.3.0/bin/$(RUBY_BASE_NAME)
	--with-pg
	--without-pg
	--enable-windows-cross
	--disable-windows-cross
	--with-pg-config
	--without-pg-config
	--with-pg_config
	--without-pg_config
	--with-pg-dir
	--without-pg-dir
	--with-pg-include
	--without-pg-include=${pg-dir}/include
	--with-pg-lib
	--without-pg-lib=${pg-dir}/lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/ss/.rvm/gems/ruby-2.3.0/extensions/x86_64-darwin-15/2.3.0/pg-0.18.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/ss/.rvm/gems/ruby-2.3.0/gems/pg-0.18.4 for inspection.
Results logged to /Users/ss/.rvm/gems/ruby-2.3.0/extensions/x86_64-darwin-15/2.3.0/pg-0.18.4/gem_make.out

**Comment by lazloth** [comment]
Answered in the other thread; **install xcode commandline tools** 
`xcode-select --install`
and **postgres**
`brew install postgresql`


fyi, i had to edit **config/initializers/assets.rb** as well but error barf will tell you what to do

**Comment by dphuang2** [comment]
Pull the new repo, it excludes postgres this time (only used it in production).
