### ISSUE TITLE
Authorization code was empty

### ISSUE THREAD

**Issue by craziplaya21** [dphuang2/PoGoBag#59]
I was running PoGoBag on my VPS just fine for several days until the past couple days, I keep getting "Authorization code was empty" whenever trying to authorize my google account to view my bag.

Log:

`craziplaya21:~/PoGoBag# rails server -b removedVPSipforpirvacy
=> Booting Puma
=> Rails 5.0.0 application starting in development on http://removedVPSipforpirvacy
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://removedVPSipforpirvacy
Use Ctrl-C to stop
Started POST "/login" for removedHOMEipforpirvacy at 2016-08-12 20:14:59 -0400
Cannot render console from removedHOMEipforpirvacy! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
  ActiveRecord::SchemaMigration Load (0.1ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by SessionsController#create as HTML
  Parameters: {"utf8"=>"▒", "authenticity_token"=>"EWSig3npEcXv2IHKCaDKAnjjmPf24Cm92ZPyTqR6xzLyWe+N8em0NzOei+cNRs0j7zm1dykM4lAj3zNtaAQTIQ==", "google"=>{"code"=>"4/cq_N3eDqaJmJRIMpfuRffAGNdZjodcwj28jUYEY2TKA"}, "commit"=>"Authorize"}
[2016-08-12T20:14:59-04:00]: DEBUG > Poke::API::RequestBuilder --: [+] Creating new request
[2016-08-12T20:14:59-04:00]: INFO  > Poke::API::RequestBuilder --: [+] Adding 'GET_PLAYER' to RPC request
[2016-08-12T20:14:59-04:00]: INFO  > Poke::API::RequestBuilder --: [+] Using Provider token
[2016-08-12T20:14:59-04:00]: DEBUG > Poke::API::RequestBuilder --: [+] Generated RPC protobuf request
<POGOProtos::Networking::Envelopes::RequestEnvelope: status_code: 2, request_id: 8145806132888207460, requests: [<POGOProtos::Networking::Requests::Request: request_type: :GET_PLAYER, request_message: "">], unknown6: nil, latitude: 0.0, longitude: 0.0, altitude: 8.0, auth_info: <POGOProtos::Networking::Envelopes::RequestEnvelope::AuthInfo: provider: "google", token: <POGOProtos::Networking::Envelopes::RequestEnvelope::AuthInfo::JWT: contents: "eyJhbGciOiJSUzI1NiIsImtpZCI6Ijk2ZWFkNWNhN2M3Zjc5OWY3OGUwNTc5ZTQ4ZjU5NWRhNmU4ZDg2ZTUifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXRfaGFzaCI6ImRuVzFDc1FhdUVGalVwN3g4UDNxV1EiLCJhdWQiOiI4NDgyMzI1MTEyNDAtNzNyaTN0N3Bsdms5NnBqNGY4NXVqOG90ZGF0MmFsZW0uYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTY2Njc2MzQ5NTI3NjY4Mzc2NTEiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXpwIjoiODQ4MjMyNTExMjQwLTczcmkzdDdwbHZrOTZwajRmODV1ajhvdGRhdDJhbGVtLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiZW1haWwiOiJjcmF6aXBsYXlhMjFAZ21haWwuY29tIiwiaWF0IjoxNDcxMDQ3Mjk5LCJleHAiOjE0NzEwNTA4OTl9.HsEQKfxJaJUw7rDGVGaDESRi4KIXhCA1EIdMHRxfsDNzp1SuXFMSzkAxfmriWFsxLan5gOTNWlxp3EquSaFNzUSFGiSs0i0fO7mUNccKmbiBbVxGRj-dlCSFCC3Ky7N7a2cdD48sQU052yK_nQY22PZviRWPkaLAeJPuwEGBDgUetVBcEO9zduk8TIg2TuEtfP-x9vaX_PqXg-lFtW5fA1sGMvY92W_ZmuSoR3bsavfXRXIrE5ux_5fQukud-pTTwrn21htUaME8IA-G-GXzVhCnc5-mCKSgaE8ZXGu2v2W3X-4IeDXJKo19F1mtelZ322gfNWFb1M-iDB9u07Il0g", unknown2: 59>>, auth_ticket: nil, unknown12: 989>
[2016-08-12T20:14:59-04:00]: DEBUG > Poke::API::RequestBuilder --: [+] Generated RPC protobuf encoded request
"\b\x02\x18\xE4\x80\x80\x80\xD0\xF0\xED\x85q\"\x02\b\x02I\x00\x00\x00\x00\x00\x00 @R\x8A\a\n\x06google\x12\xFF\x06\n\xFA\x06eyJhbGciOiJSUzI1NiIsImtpZCI6Ijk2ZWFkNWNhN2M3Zjc5OWY3OGUwNTc5ZTQ4ZjU5NWRhNmU4ZDg2ZTUifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXRfaGFzaCI6ImRuVzFDc1FhdUVGalVwN3g4UDNxV1EiLCJhdWQiOiI4NDgyMzI1MTEyNDAtNzNyaTN0N3Bsdms5NnBqNGY4NXVqOG90ZGF0MmFsZW0uYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTY2Njc2MzQ5NTI3NjY4Mzc2NTEiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXpwIjoiODQ4MjMyNTExMjQwLTczcmkzdDdwbHZrOTZwajRmODV1ajhvdGRhdDJhbGVtLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiZW1haWwiOiJjcmF6aXBsYXlhMjFAZ21haWwuY29tIiwiaWF0IjoxNDcxMDQ3Mjk5LCJleHAiOjE0NzEwNTA4OTl9.HsEQKfxJaJUw7rDGVGaDESRi4KIXhCA1EIdMHRxfsDNzp1SuXFMSzkAxfmriWFsxLan5gOTNWlxp3EquSaFNzUSFGiSs0i0fO7mUNccKmbiBbVxGRj-dlCSFCC3Ky7N7a2cdD48sQU052yK_nQY22PZviRWPkaLAeJPuwEGBDgUetVBcEO9zduk8TIg2TuEtfP-x9vaX_PqXg-lFtW5fA1sGMvY92W_ZmuSoR3bsavfXRXIrE5ux_5fQukud-pTTwrn21htUaME8IA-G-GXzVhCnc5-mCKSgaE8ZXGu2v2W3X-4IeDXJKo19F1mtelZ322gfNWFb1M-iDB9u07Il0g\x10;`\xDD\a"
[2016-08-12T20:14:59-04:00]: INFO  > Poke::API::RequestBuilder --: [+] Executing RPC request
[2016-08-12T20:15:00-04:00]: INFO  > Poke::API::Response       --: [+] Decoding Main RPC responses
[2016-08-12T20:15:00-04:00]: DEBUG > Poke::API::Response       --: [+] RPC response
"<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx/1.11.1</center>\r\n</body>\r\n</html>\r\n"
[2016-08-12T20:15:00-04:00]: INFO  > Poke::API::Client         --: [+] Cleaning up RPC requests
  Rendering static_pages/home.html.erb within layouts/application
  Rendered sessions/_login.html.erb (10.0ms)
  Rendered static_pages/home.html.erb within layouts/application (265.6ms)
  Rendered static_pages/_donate_small.html.erb (0.2ms)
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."name" IS NULL LIMIT ?  [["LIMIT", 1]]
  Rendered layouts/_header.html.erb (10.7ms)
Completed 200 OK in 540ms (Views: 350.7ms | ActiveRecord: 0.5ms)
`

**Comment by dphuang2** [comment]
Search up 403 error for the significance of it. The VPS you are using just got blocked...sorry D:

**Comment by craziplaya21** [comment]
Is there a way to run PoGoBag through a proxy?
