### ISSUE TITLE
Error after starting Rails and going to local host

### ISSUE THREAD

**Issue by Gnommego** [dphuang2/PoGoBag#6]
LoadError in StaticPagesController#home
No such file to load -- google/protobuf_c

Extracted source (around line #2):
1
2
3
4
5
6
              
module SessionsHelper
  require 'poke-api'
  require 'pp'

  def current_user
    if (name = session[:pogo_alias])

Rails.root: C:/Sites/PoGoBag

Application Trace | Framework Trace | Full Trace
app/helpers/sessions_helper.rb:2:in `<module:SessionsHelper>'
app/helpers/sessions_helper.rb:1:in `<top (required)>'
app/controllers/application_controller.rb:1:in `<top (required)>'
app/controllers/static_pages_controller.rb:1:in `<top (required)>'
This error occurred while loading the following files:
   poke-api
   poke-api/POGOProtos/Signature
   google/protobuf
   google/protobuf_c
Request

Parameters:

None

**Comment by eXeLe** [comment]
#1

**Comment by dphuang2** [comment]
Closing this as it is the same question as #1
