### ISSUE TITLE
Unable to access remotely

### ISSUE THREAD

**Issue by alowva** [dphuang2/PoGoBag#7]
installed on Ubuntu server I can access the webui using locahost:3000, confirmed using curl and using ssh tunneling.

however when I try to access from another machine on my network I get connection refused.

I have enabled port 3000 in the local firewall but that doesn't seem to work, is this set up somehow to block anything but local connections?

any recommendations on firewall changes?

Thanks

**Comment by KennethRuys** [comment]
Start the program with the command "rails s -b 0.0.0.0". This allows connections to the IP of the server from any address instead of just from localhost. The maker announced a guide but it isn't here yet so this will do for now

**Comment by dphuang2** [comment]
I will be putting up how to do this with ngrok soon.

**Comment by felixvd** [comment]
I was hosting on a VPS running Ubuntu but couldn't access it, although I was sure the firewall was open. Calling "rails s -b 0.0.0.0" fixed it. Thanks.
