### ISSUE TITLE
Missing google/protobuf_c

### ISSUE THREAD

**Issue by PassyFox** [dphuang2/PoGoBag#8]
After i done everything and started rails this was what greeted me. How does one install the ProtoBuff

![screenshot 5](https://cloud.githubusercontent.com/assets/20614880/17487296/8ebaf8ca-5d94-11e6-8e4e-09f09904a44c.png)

**Comment by chaotic-kitten** [comment]
I also have this issue.

**Comment by dphuang2** [comment]
Please run "bundle" inside the project directory and copy the output here.

**Comment by Gnommego** [comment]
C:\Users\admin\Documents\poke\PoGoBag>bundle
Using rake 11.2.2
Using concurrent-ruby 1.0.2
Using i18n 0.7.0
Using minitest 5.9.0
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using pkg-config 1.1.7
Using rack 2.0.1
Using nio4r 1.2.1
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using arel 7.1.1
Using net-ssh 3.2.0
Using execjs 2.7.0
Using sass 3.4.22
Using method_source 0.8.2
Using thor 0.19.1
Using will_paginate 3.1.0
Using capistrano-harrow 0.5.3
Using chronic 0.10.2
Using coffee-script-source 1.10.0
Using debug_inspector 0.0.2
Using ffi 1.9.14
Using geocoder 1.3.7
Using google-protobuf 3.0.0.alpha.5.0.5.1
Using multi_xml 0.5.5
Using httpclient 2.8.0
Using multi_json 1.12.1
Using rb-fsevent 0.9.7
Using ruby-xxHash 0.4.0.1
Using puma 3.6.0
Using bundler 1.12.5
Using tilt 2.0.5
Using spring 1.7.2
Using sqlite3 1.3.11
Using turbolinks-source 5.0.0
Using tzinfo 1.2.2
Using nokogiri 1.6.8
Using rack-test 0.6.3
Using sprockets 3.7.0
Using websocket-driver 0.6.4
Using mime-types 3.1
Using net-scp 1.2.1
Using autoprefixer-rails 6.4.0.1
Using uglifier 3.0.1
Using bootstrap-will_paginate 0.0.10
Using whenever 0.9.7
Using coffee-script 2.4.1
Using rb-inotify 0.9.7
Using httparty 0.14.0
Using turbolinks 5.0.1
Using activesupport 5.0.0
Using tzinfo-data 1.2016.6
Using loofah 2.0.3
Using mail 2.6.4
Using sshkit 1.11.2
Using bootstrap-sass 3.3.7
Using listen 3.0.8
Using gpsoauth-rb 0.1.2
Using rails-dom-testing 2.0.1
Using globalid 0.3.7
Using activemodel 5.0.0
Using jbuilder 2.6.0
Using rails-html-sanitizer 1.0.3
Using airbrussh 1.1.0
Using spring-watcher-listen 2.0.0
Using poke-go-api 0.1.1 from https://github.com/nabeelamjad/poke-api.git (at master@e95cfdc)
Using activejob 5.0.0
Using activerecord 5.0.0
Using actionview 5.0.0
Using capistrano 3.6.0
Using actionpack 5.0.0
Using capistrano-bundler 1.1.4
Using capistrano-passenger 0.2.0
Using capistrano-rvm 0.1.2
Using actioncable 5.0.0
Using actionmailer 5.0.0
Using railties 5.0.0
Using sprockets-rails 3.1.1
Using capistrano-rails 1.1.7
Using bootstrap-social-rails 4.12.0
Using coffee-rails 4.2.1
Using font-awesome-rails 4.6.3.1
Using jquery-rails 4.1.1
Using jquery-tablesorter 1.22.1
Using web-console 3.3.1
Using zeroclipboard-rails 0.1.2
Using rails 5.0.0
Using sass-rails 5.0.6
Using capistrano-rails-collection 0.0.3
Bundle complete! 30 Gemfile dependencies, 92 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

**Comment by dphuang2** [comment]
Take a look at the full setup now. I believe this fixes the issue by installing the requirements correctly.

**Comment by Gnommego** [comment]
I tried going in and doing a fresh install with your updated readme and it is still giving the protobuf error

**Comment by PassyFox** [comment]
i have the exact same output except 1 more "Using pg 0.18.4"

**Comment by PassyFox** [comment]
Fixed in latest installs just follow the setup instructions to the letter!

**Comment by weblack** [comment]
I'm getting this error as well.

```
$ c:/ruby22/bin/bundle install --without production
Using rake 11.2.2
Using concurrent-ruby 1.0.2
Using i18n 0.7.0
Using minitest 5.9.0
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using pkg-config 1.1.7
Using rack 2.0.1
Using nio4r 1.2.1
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using arel 7.1.1
Using net-ssh 3.2.0
Using angularjs-rails 1.5.6
Using execjs 2.7.0
Using sass 3.4.22
Using method_source 0.8.2
Using thor 0.19.1
Using will_paginate 3.1.0
Using capistrano-harrow 0.5.3
Using chronic 0.10.2
Using coffee-script-source 1.10.0
Using debug_inspector 0.0.2
Using ffi 1.9.14
Using geocoder 1.3.7
Using google-protobuf 3.0.0
Using multi_xml 0.5.5
Using httpclient 2.8.0
Using multi_json 1.12.1
Using rb-fsevent 0.9.7
Using ruby-xxHash 0.4.0.1
Using puma 3.6.0
Using bundler 1.12.5
Using tilt 2.0.5
Using spring 1.7.2
Using sqlite3 1.3.11
Using turbolinks-source 5.0.0
Using tzinfo 1.2.2
Using nokogiri 1.6.8
Using rack-test 0.6.3
Using sprockets 3.7.0
Using websocket-driver 0.6.4
Using mime-types 3.1
Using net-scp 1.2.1
Using autoprefixer-rails 6.4.0.1
Using uglifier 3.0.1
Using bootstrap-will_paginate 0.0.10
Using whenever 0.9.7
Using coffee-script 2.4.1
Using rb-inotify 0.9.7
Using httparty 0.14.0
Using turbolinks 5.0.1
Using activesupport 5.0.0
Using tzinfo-data 1.2016.6
Using loofah 2.0.3
Using mail 2.6.4
Using sshkit 1.11.2
Using bootstrap-sass 3.3.7
Using listen 3.0.8
Using gpsoauth-rb 0.1.2
Using rails-dom-testing 2.0.1
Using globalid 0.3.7
Using activemodel 5.0.0
Using jbuilder 2.6.0
Using rails-html-sanitizer 1.0.3
Using airbrussh 1.1.0
Using spring-watcher-listen 2.0.0
Using poke-go-api 0.1.0 from https://github.com/nabeelamjad/poke-api.git (at 0.1.0@56603aa)
Using activejob 5.0.0
Using activerecord 5.0.0
Using actionview 5.0.0
Using capistrano 3.6.0
Using actionpack 5.0.0
Using capistrano-bundler 1.1.4
Using capistrano-passenger 0.2.0
Using capistrano-rvm 0.1.2
Using actioncable 5.0.0
Using actionmailer 5.0.0
Using railties 5.0.0
Using sprockets-rails 3.1.1
Using capistrano-rails 1.1.7
Using bootstrap-social-rails 4.12.0
Using coffee-rails 4.2.1
Using font-awesome-rails 4.6.3.1
Using jquery-rails 4.1.1
Using jquery-tablesorter 1.22.1
Using web-console 3.3.1
Using zeroclipboard-rails 0.1.2
Using rails 5.0.0
Using sass-rails 5.0.6
Using capistrano-rails-collection 0.0.3
Bundle complete! 32 Gemfile dependencies, 93 gems now installed.
Gems in the group production were not installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

**Comment by br0x** [comment]
The same error on Ubuntu 16.04
No such file to load -- google/protobuf
