### ISSUE TITLE
run pogobag from port forward?

### ISSUE THREAD

**Issue by imattv2** [dphuang2/PoGoBag#81]
just wanted to know if its possible to run pogobag through a NAT server or not? I wasnt able to find a discord thread, so posting via issue was my only reasonable call for help.

i tried rails s -p 3000 and then rerouting to it via myip:3000 from my phone, but it doesnt load (i probably did something wrong with cmd)

cmd shows:

=> Booting Puma
=> Rails 5.0.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
  Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?
  Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?
*** SIGUSR2 not implemented, signal based restart unavailable!
*** SIGUSR1 not implemented, signal based restart unavailable!
*** SIGHUP not implemented, signal based logs reopening unavailable!
Puma starting in single mode...
* Version 3.6.0 (ruby 2.2.5-p319), codename: Sleepy Sunday Serenity
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:300

**Comment by Dajen** [comment]
You just need to run it with flag    `-b 0.0.0.0` Then the server will listen on any IP, not just localhost.

So the whole command would be `rails s -b 0.0.0.0` then you will be able to reach from internet on address _yourIP:3000_
