### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by RomainGoncalves** [dphuang2/PoGoBag#82]
Hey,

great app you made. But I'm baffled, how/where do you get the data from? I mean, do you request the game developer's servers, or just having access to user's google account enough?

I'm really surprised how well it all works.

Thanks for any response.

**Comment by mushishi06** [comment]
Hi, 
Yes this app use the API (game developer's servers) so he add a warning on the README.md
user's google account doesn't store any data from Pokemon Go

**Comment by RomainGoncalves** [comment]
Thanks for that. It must be a massive breach of the terms.
