### ISSUE TITLE
I Know i am doing something wrong.

### ISSUE THREAD

**Issue by Evixor** [dphuang2/PoGoBag#84]
I am at this stage of setting up local server:

4) Install all dependencies: 
bundle install --without production
5) Run database setup and start the server 
rake db:setup
rails s
I keep getting message that doesn't know what bundle is. I have a windows open in the pogobag directory and I type as stated above but keep getting error.
Please tell me what I am doing wrong, I know I am overlooking something but I am at a lose.

Thank you for this program and your help.
Evixor

**Comment by Dajen** [comment]
Did you do all the steps from the first part?

**Windows:**

1) Install Ruby 2.2.5 [http://rubyinstaller.org/downloads/](http://rubyinstaller.org/downloads/) 
_x64 for 64-bit system and regular install for 32-bit system_ 
2) Install Ruby DevKit [http://rubyinstaller.org/downloads/](http://rubyinstaller.org/downloads/) 
_Same link but at the bottom. Follow same logic for x64 as the above step_ 
2a) Create a new directory to extract the Ruby DevKit into 
2b) Run these commands:
```
cd <RubyDev Path>
ruby dk.rb init
ruby dk.rb install
```
3) Install Node.js 4.4.7 [https://nodejs.org/en/](https://nodejs.org/en/) 
4) Install Git [https://git-scm.com/downloads](https://git-scm.com/downloads)
5) Run these two commands in terminal: 

```
gem install rails
gem install bundler
```

**Comment by Evixor** [comment]
I did all of thoses steps, all worked in thoses steps.
