### ISSUE TITLE
ExecJS::ProgramError in StaticPages#home

### ISSUE THREAD

**Issue by ritam1806** [dphuang2/PoGoBag#9]
Showing C:/Users/phone/Home/PoGoBag/app/views/static_pages/home.html.erb where line #2 raised:

TypeError: Object doesn't support this property or method
Extracted source (around line #2):
1
2
3
4
5
6
              
<div class="home-page-wrap"
     style="background-image: url(<%=image_path 'background-home.png'%>)">
  <div class="container">
    <div class="home-page">
      <div class="landing-title">
        <h1><%= image_tag 'itemstorageupgrade.1.png' %>PoGoBag</h1>

Rails.root: C:/Users/phone/Home/PoGoBag

![untitled](https://cloud.githubusercontent.com/assets/20911947/17491566/c667adbe-5dc5-11e6-9c8d-eefa17a816f9.png)

After Running rails s ..... opening browser showing this ERROR .... please help

**Comment by saugon** [comment]
You need to install NodeJS: https://nodejs.org/en/download/

**Comment by dphuang2** [comment]
nodejs is required to compile JavaScript.

`sudo apt-get install nodejs`

**Comment by ritam1806** [comment]
Thanks.... That Helped :+1:
