### ISSUE TITLE
Authorization code was empty

### ISSUE THREAD

**Issue by josuedelatorre35** [dphuang2/PoGoBag#95]
Recently I've been stuck with this issue and I haven't been able to find a fix. Even though I paste the authorization code into the box, I get the "Authorization code was empty" error. I also tried logging in from my Android phone instead of my PC, but I still got the same issue

**Comment by Dirtpants** [comment]
Im having the same issue....tried 4 different browsers, phone, tablet and nothing....

**Comment by dphuang2** [comment]
Seems like Niantic blocked the server again. When I find a time I will migrate it to a new host.

**Comment by Dirtpants** [comment]
Awesome! Thanks for your hard work!


Sent from my Sprint Samsung Galaxy® Note 4.

-------- Original message --------

**Comment by iKristy** [comment]
I get the same `Authorization code was empty` error message, although I'm not even using Google Authentification but the PTC login. Do you know when this might be fixed @dphuang2?

**Comment by DrSMaro** [comment]
Learned just how dependent I am on Pogobag over the weekend.  Looking forward to using the website again.  Please share status or insight @dphuang2!  It's a beautiful website and tool that so many of us love using!  Without it the game becomes too bland.  

Thanks in advance!  Looking forward to your reply!  Please fix! :) <3

**Comment by Dirtpants** [comment]
For real!!! I can't play without it!


Sent from my Sprint Samsung Galaxy® Note 4.

-------- Original message --------

**Comment by juggalokyle** [comment]
This site has been down for too many days. Checking my Pokemon manually is way too tedious and time consuming. I need pogobag.me in my life please!!!

**Comment by dphuang2** [comment]
Just migrated server, pogobag.me is up again.

**Comment by Dirtpants** [comment]
I heart you


Sent from my Sprint Samsung Galaxy® Note 4.

-------- Original message --------
